// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvejtjcgeomyiajxxyxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2ZWp0amNnZW9teWlhanh4eXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMTk3MjIsImV4cCI6MjA2NDg5NTcyMn0.hrm0KlY_x2dTu4YciCt_-n9utg3tvSxLJfhNNdPX4Bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);